import type { BuildingDef, BuildingType, TroopDef, TroopType } from "./types";

/** geometric helper: base * mult^(level-1), rounded */
const scale = (base: number, mult: number) => (level: number) =>
  Math.round(base * Math.pow(mult, level - 1));

export const GRID_SIZE = 16;

export const BUILDINGS: Record<BuildingType, BuildingDef> = {
  townhall: {
    type: "townhall",
    name: "Town Hall",
    emoji: "🏛️",
    category: "core",
    size: 3,
    maxLevel: 6,
    requiredTh: 1,
    limitByTh: [0, 1, 1, 1, 1, 1, 1],
    cost: (l) => ({ gold: scale(1000, 3)(l - 1) }),
    buildTime: (l) => Math.round(30 * Math.pow(2.2, l - 1)),
    hp: scale(1500, 1.3),
  },
  goldmine: {
    type: "goldmine",
    name: "Gold Mine",
    emoji: "⛏️",
    category: "resource",
    size: 2,
    maxLevel: 8,
    requiredTh: 1,
    limitByTh: [0, 1, 2, 3, 4, 5, 6],
    cost: (l) => ({ elixir: scale(150, 1.6)(l) }),
    buildTime: (l) => Math.round(20 * Math.pow(1.7, l - 1)),
    production: {
      resource: "gold",
      perMin: scale(40, 1.35),
      cap: scale(800, 1.5),
    },
    hp: scale(400, 1.2),
  },
  elixircollector: {
    type: "elixircollector",
    name: "Elixir Collector",
    emoji: "🧪",
    category: "resource",
    size: 2,
    maxLevel: 8,
    requiredTh: 1,
    limitByTh: [0, 1, 2, 3, 4, 5, 6],
    cost: (l) => ({ gold: scale(150, 1.6)(l) }),
    buildTime: (l) => Math.round(20 * Math.pow(1.7, l - 1)),
    production: {
      resource: "elixir",
      perMin: scale(40, 1.35),
      cap: scale(800, 1.5),
    },
    hp: scale(400, 1.2),
  },
  goldstorage: {
    type: "goldstorage",
    name: "Gold Storage",
    emoji: "🏦",
    category: "storage",
    size: 2,
    maxLevel: 8,
    requiredTh: 1,
    limitByTh: [0, 1, 1, 2, 2, 3, 3],
    cost: (l) => ({ elixir: scale(300, 1.7)(l) }),
    buildTime: (l) => Math.round(25 * Math.pow(1.8, l - 1)),
    storage: { resource: "gold", capacity: scale(5000, 1.7) },
    hp: scale(800, 1.25),
  },
  elixirstorage: {
    type: "elixirstorage",
    name: "Elixir Storage",
    emoji: "🛢️",
    category: "storage",
    size: 2,
    maxLevel: 8,
    requiredTh: 1,
    limitByTh: [0, 1, 1, 2, 2, 3, 3],
    cost: (l) => ({ gold: scale(300, 1.7)(l) }),
    buildTime: (l) => Math.round(25 * Math.pow(1.8, l - 1)),
    storage: { resource: "elixir", capacity: scale(5000, 1.7) },
    hp: scale(800, 1.25),
  },
  barracks: {
    type: "barracks",
    name: "Barracks",
    emoji: "⚔️",
    category: "army",
    size: 2,
    maxLevel: 6,
    requiredTh: 1,
    limitByTh: [0, 1, 1, 2, 2, 2, 3],
    cost: (l) => ({ elixir: scale(200, 1.8)(l) }),
    buildTime: (l) => Math.round(30 * Math.pow(1.8, l - 1)),
    hp: scale(350, 1.2),
  },
  armycamp: {
    type: "armycamp",
    name: "Army Camp",
    emoji: "⛺",
    category: "army",
    size: 2,
    maxLevel: 6,
    requiredTh: 1,
    limitByTh: [0, 1, 1, 2, 2, 3, 4],
    cost: (l) => ({ elixir: scale(250, 1.8)(l) }),
    buildTime: (l) => Math.round(30 * Math.pow(1.8, l - 1)),
    housing: scale(20, 1.4),
    hp: scale(300, 1.2),
  },
  cannon: {
    type: "cannon",
    name: "Cannon",
    emoji: "💣",
    category: "defense",
    size: 2,
    maxLevel: 8,
    requiredTh: 1,
    limitByTh: [0, 2, 2, 3, 4, 5, 6],
    cost: (l) => ({ gold: scale(250, 1.6)(l) }),
    buildTime: (l) => Math.round(20 * Math.pow(1.7, l - 1)),
    defense: { hp: scale(420, 1.25), dps: scale(11, 1.3), range: 5 },
  },
  archertower: {
    type: "archertower",
    name: "Archer Tower",
    emoji: "🏹",
    category: "defense",
    size: 2,
    maxLevel: 8,
    requiredTh: 2,
    limitByTh: [0, 0, 1, 2, 3, 4, 5],
    cost: (l) => ({ gold: scale(500, 1.6)(l) }),
    buildTime: (l) => Math.round(25 * Math.pow(1.7, l - 1)),
    defense: { hp: scale(380, 1.25), dps: scale(9, 1.3), range: 7 },
  },
  wall: {
    type: "wall",
    name: "Wall",
    emoji: "🧱",
    category: "wall",
    size: 1,
    maxLevel: 6,
    requiredTh: 2,
    limitByTh: [0, 0, 25, 50, 75, 100, 150],
    cost: (l) => ({ gold: scale(100, 2)(l) }),
    buildTime: () => 1,
    defense: { hp: scale(600, 1.4), dps: () => 0, range: 0 },
  },
};

export const BUILD_ORDER: BuildingType[] = [
  "townhall",
  "goldmine",
  "elixircollector",
  "goldstorage",
  "elixirstorage",
  "cannon",
  "archertower",
  "wall",
  "barracks",
  "armycamp",
];

export const TROOPS: Record<TroopType, TroopDef> = {
  barbarian: {
    type: "barbarian",
    name: "Barbarian",
    emoji: "🪓",
    cost: { elixir: 25 },
    housing: 1,
    trainTime: 5,
    hp: 80,
    dps: 18,
    speed: 2.2,
    range: 0.6,
    prefersDefense: false,
  },
  archer: {
    type: "archer",
    name: "Archer",
    emoji: "🏹",
    cost: { elixir: 50 },
    housing: 1,
    trainTime: 8,
    hp: 40,
    dps: 16,
    speed: 2.6,
    range: 3.5,
    prefersDefense: false,
  },
  giant: {
    type: "giant",
    name: "Giant",
    emoji: "🗿",
    cost: { elixir: 250 },
    housing: 5,
    trainTime: 30,
    hp: 420,
    dps: 14,
    speed: 1.4,
    range: 0.7,
    prefersDefense: true,
  },
};

export const TROOP_ORDER: TroopType[] = ["barbarian", "archer", "giant"];
